server:
  port: 9006
spring:
  application:
    name: zuul
  redis:
    host: 10.0.41.102:6379
    password: 123qwe
  datasource:
      url: jdbc:mysql://10.0.41.102:3306/xiaowei_20190419?useSSL=false
      username: man
      password: qwe123
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    service-person: /person/**
    service-entry: /entry/**
  ignored-services: '*'
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.example.base.sys.entity


