server:
  port: 8763
spring:
  profiles:
    include: base
  application:
    name: service-entry
  datasource:
    url: jdbc:mysql://10.0.41.102:3306/xiaowei_20190419?useSSL=false
    username: man
    password: qwe123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.example.base.sys.entity
